language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
    - PART=1/4
    - PART=2/4
    - PART=3/4
    - PART=4/4
sudo: required
jobs:
  include:
    - stage: regenerate build.jl
      script: julia build_tarballs.jl --only-buildjl
      if: tag IS present
before_script:
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
- julia build_tarballs.jl --part=$PART
deploy:
  provider: releases
  api_key:
      # Note; this api_key is only valid for JuliaPackaging/CMakeBuilder; you need
      # to make your own: https://docs.travis-ci.com/user/deployment/releases/
    secure: H/TrZPbYVvvvluGEDdsZQJo2C3RZ3RvSUPSN7VCOt21YpSc/ToCzT4+3C81kC9inxHYIaMWDm0Jl7Oba/QaJ7VaaDjjIgnrYx9IUMSzHuJBzNl8FFyXdA4/e0H1/Kzr89P4nzVYfoAsaawLJlu7cI9OWX94PHDlq3BKF52/52EYk71GepUDBtYigltgGdlwoUQKD8DJq/HbQnsYmCLaGKVesBXsdkKnrFfxVdcYCqDeIMe7pk/wzUcbr7AVAe7FybRcdQdv/qN2sO3i8Fcvt9rbIRSjioH5nTRoW233tvr0CJGmIW/xRPOPAYa8hhGJg7dXRLnrhUJalx9jRKnAT490/mXAPChk0hmHsmhw5PPiTAXVQ/WNJalN7XVB33JvXWJue6uvag8lapt2xjurpg5oWnw+AYKN+zaROrxtgTWYeLFWk0P8Z6JmN5fc05CAhW6qbnmUOD/jK9LY+XU0beREDTNlJCy3/7xUne7ATQ5iWZawBDZoDCTQfhVbVnpAJnenmA49vwgciTX36xaWyaPIhy4vtxftjOGE0kxmeGkRGz2xuTcg/SAJvvV6cec1ig7JAC5yRt0cbXsbnqfrAvtJmAlfFiVCo3FM4cmriI5cHgLATXNP9E6c2+Tc4sjXgw+N4eXROh9Z4MAns78Y2/cSeZF2fcFeIpwBcNxNboNE=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: JuliaPackaging/CMakeBuilder
    tags: true
